### ISSUE TITLE
Need instructions how to work with this project

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-schema#13]
I am coming in naively. I cloned the repo. I looked at the README. And now I am exploring...

```
❯ make all
poetry run gen-project --config-file config.yaml -d project src/datalad_schema/schema/datalad_schema.yaml && mv project/*.py src/datalad_schema/datamodel
Command not found: gen-project
make: *** [Makefile:107: gen-project] Error 1
```

Ah, `make` suggests: "make setup -- initial setup (run this first)"

This does something! A lot, actually. It should probably be mentioned that `poetry` is needed.

Looking at what it did: I don't think that was the correct action. I have dependencies installed now (unclear where they ended up, though), but I also modified the repo with an `chore: initial commit` -- which I had no intention of making.

`setup` is: `install gen-project gen-examples gendoc git-init-add`

So maybe some of them are needed, and some not.

`poetry env info` informs me that I got a dedicated venv under `/home/mih/.cache/pypoetry/virtualenvs`

I can perform the `install` Makefile step with `poetry install` and avoid the git repo modification. This should be a one-time setup action.

A `make gen-project` seems to build all the stuff from the linkml sources (owl, ttl, jsonld, shacl, py, xlsx). The output is not Git friendly -- a timestamp is included. Why?

A `make gen-example` is just copying static files from A to B. Into `./examples` to be precise. Strangely, some files in there are committed. The sources are in `src/data/examples/`. Unclear why they would be committed in two different places.

A `make gendoc` seems to have no impact on the repo. No wait, it populates `./docs` -- and this one is git-ignored. I wonder if that should also be the case for `./examples/`.

The remaining dependencies of `make setup` are Git calls. It feels as if they have the intention to avoid contact with Git and hide it behind `make` -- if that is true, we should not play that game.

**Comment by mih** [comment]
A large number of locations are gitignored in this project! `.gitignore` is 133 lines

**Comment by jsheunis** [comment]
My understanding is that with each `make setup` or `make all` the generators configured in https://github.com/psychoinformatics-de/datalad-schema/blob/main/config.yaml will run and update the corresponding outputs in `/project/...`. I think it's up to use to decide how we want to configure these generators and if we indeed want configured generators to provide updated outputs after each change to the schema YAML file.

**Comment by mih** [comment]
Looking deeper, I believe that the only files with information are in `src/` (apart from the README). The rest is all auto-generated.

`src/datalad_schema/schema/datalad_schema.yaml` is the main model file.

The purpose of the `.py` and `.json` files in `src/` is unclear to me right now.

**Comment by jsheunis** [comment]
> Ah, make suggests: "make setup -- initial setup (run this first)"
>
> This does something! A lot, actually. It should probably be mentioned that poetry is needed.
>
> Looking at what it did: I don't think that was the correct action. I have dependencies installed now (unclear where they ended up, though), but I also modified the repo with an chore: initial commit -- which I had no intention of making.
> 
> setup is: install gen-project gen-examples gendoc git-init-add
>
> So maybe some of them are needed, and some not.

My interpretation: those are steps needed for the initial setup of the repo (hence the git commit), not per user. I did those steps, but then as soon as someone tries to do it next, their process fails.

**Comment by mih** [comment]
This project has been superseded by https://github.com/psychoinformatics-de/datalad-concepts

Closing.
