### ISSUE TITLE
Create leaner repository structure

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/datalad-schema#15]
comments from @mih:

> - let's have src/ and nothing under it is generated ever, and everything is committed
> - let's have ONE output location, nothing under it is committed, ever
> - Let's strip the cookiecutter/cruft setup. It seems its benefits are limited and the cost high. it least for now, we are not planning on having many of these repos

**Comment by jsheunis** [comment]
@mslw created a draft example here: https://github.com/sfb1451/crc-schema-draft, published at https://sfb1451.github.io/crc-schema-draft/

**Comment by mih** [comment]
This project has been superseded by https://github.com/psychoinformatics-de/datalad-concepts

Closing.
